### ISSUE TITLE
is there an "automatic creation of indexes" feature?

### ISSUE THREAD

**Issue by bebor** [Wiredcraft/loopback-connector-couchdb#3]
https://www.npmjs.com/package/loopback-connector-apachecouchdb (github: https://github.com/akat/loopback-couch-connector) has a nice and working automatic creation of indexes. does you connector has this feature as well?

the issue is that the automatic creation of indexes works fine in loopback-couch-connector, but the filtering somehow does not work for me there at all.

yous connector'sfiltering  works, but the automatic creation of indexes i do miss. are you planning to implement it?

**Comment by makara** [comment]
We don't have the feature nor the plan (yet). I'd recommend using the views directly (see Readme). Personally I feel the "auto index" and "find by filters" etc are only sugars and over-engineered. But still, you are more than welcome to tell us how it should be implemented or shoot us a PR.

**Comment by bebor** [comment]
+1
